/** Level titles ordered by experience level for the header progression label. */
export const RANK_TITLES: string[] = [
  "Dammråtte-tämjare",
  "Pryl-pionjär",
  "Småfixar-smurfen",
  "Kaos-kontrollant",
  "Städ-lärling",
  "Slipp-stök-strateg",
  "Proffs-putsare",
  "Städ-ninja",
  "Hemmets Högra Hand",
  "Fixar-fantom",
  "Fixar-drottning",
  "Ordningens Väktare",
  "Struktur-stjärna",
  "Glans-general",
  "Hushållets Hjärta",
  "Magisk Miljö-skapare",
  "Ordningens Överstepräst",
  "Guldputs-guvernör",
  "Fixar-fenomen",
  "Suverän Syssle-specialist",
  "Universums Fixar-fyrstinna",
  "Intergalaktisk Ordningsexpert",
  "Odödlig Fixar-legend 🏆",
]
